### ISSUE TITLE
Beobachtungen devlinked.swissbib.ch (part 1)

### ISSUE THREAD

**Issue by guenterh** [swissbib/linked.integration.projekt#1]
Stand:
https://github.com/swissbib/vufind/commit/cefa354c51099ae82675076dada7d2b1c94a8fba

@ema-om @outermedia-cbo @witzigs 

Hallo, ich halte hier einfach mal fest was mir bei meiner lokalen Installation (entspricht http://devlinked.swissbib.ch/) auffällt (damit ich nicht gleich wieder alles vergesse). Es ist gut möglich, dass ich mir die eine oder andere Frage auch selber beantworten kann, wenn ich tiefer in den code einsteige. Deshalb nicht wundern...

- [ ] warum erhalte ich bei den von Eddi angegeben links nicht mehr Inhalt für die knowledge card?
Merke gerade, dass für Jane Austin Inhalt angezeigt wird, alle anderen sind noch empty
http://devlinked.swissbib.ch/Card/Knowledge/Author/d792881e-1e3e-36df-8489-a6c3ba957e24
- na ja, ganz einfach, weil die Testpersonen nicht mit z.B. DBPedia verlinkt sind....
- wie komme ich an sinnvolle weitere Beispiele:
bitte gegen den Elasticsearchindex z.B. diese Abfrage absetzten:

 curl -XGET 'sb-ues1.swissbib.unibas.ch:8080/lsb/person/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "query": {
        "exists" : { "field" : "dbp:deathDate" }
    }
}
'
(oder andere Felder die aus DBPedia hinzugefügt worden sind
Dann erhalte ich mit sinnvollen Daten für die Anzeige, z.B,
7fe5a372-5b2a-398b-88c1-0c06233d9ed4

@witzigs 
bitte bei uns im Netz einen Tunnel bauen und dann die Abfrage mit localhost anstelle von sb-ues1

- [ ] autosuggestion
- wenn ich die Startseite aufrufe (devlinked.swissbib.ch) und einen Suchterm eingebe (egal ob ein, zwei drei oder mehr Zeichen, ebenso ist die Eingabegeschwindigkeit egal) erhalte ich zuerst mal keine Vorschläge.
- wenn ich dann nach der Eingabe dieser ersten Zeichen kurz innehalte und anschliessend ein weiteres Zeichen eingebe (oder eines lösche) werden Vorschläge angezeigt. 
- dieses Verhalten tritt nicht mehr auf, wenn ich die Eingabe (auch nach einem Suchvorschlag) wieder lösche und erneut Zeichen eingebe
- erst wenn die Seite wieder frisch aufgebaut worden ist, tritt dieses Verhalten wieder auf
- scheint mir nur bei der Startseite aufzutreten, nein unterdessen habe ich das auch mal in anderen Kontexten gehabt  

- [ ] s. https://github.com/swissbib/linked.integration.projekt/issues/1#issuecomment-354787293

- [x] @outermedia-cbo willst Du Dich hier nicht als Author eintragen (und bei anderen über die ich noch nicht gestolpert bin)? https://github.com/swissbib/vufind/blob/knowledge-cards/module/ElasticSearch/src/ElasticSearch/VuFind/Search/Results/Factory.php#L11

- [ ]  @outermedia-cbo  https://github.com/swissbib/vufind/blob/knowledge-cards/module/ElasticSearch/src/ElasticSearch/VuFind/Search/Results/Factory.php#L30 braucht es die config in den results nicht? Dann würde ich sie ganz weglassen

- [ ] noch zu autosuggestion
@ema-om 
im Moment wird für jede section der autosuggestion box der gleiche search handler aufgerufen
(womit die Ergebnisse für alle Abschnitte gleich sind)
- Ist die Suche für die einzelnen Abschnitte konfigurierbar (sollte sein)? wo und wie?
im Moment löst die Funktion "show all results" auch noch keinen request aus (obwohl unterschiedliche search handler aufgenommen werden (type=title / type=author / type=topic)

**Comment by guenterh** [comment]
Initialisierung der Controller
- Knowledge Card Controller wird über den generic Mechanismus von VuFind initialisiert
https://github.com/swissbib/vufind/blob/knowledge-cards/module/Swissbib/src/Swissbib/Controller/Factory.php#L53
- dabei wird dem Controller der ServiceLocator als dependency übergeben
- VuFind macht das auch im aktuellen master branch noch so (wenn keine spezialisierte Factory Methode verwendet wird)
https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Controller/GenericFactory.php#L56
- im AbstractAction Typ des Zend-Frameworks ist diese Methode jedoch bereits deprecated (und in ZF3 gar nicht mehr möglich)
https://github.com/zendframework/zend-mvc/blob/release-2.7/src/Controller/AbstractController.php#L249
https://github.com/zendframework/zend-mvc/blob/master/src/Controller/AbstractController.php
@edelm wir sollten uns überlegen, wie wir damit vorausschauend umgehen (für linked integration nicht mehr relevant) - weisst Du wie VuFind vorgeht?

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1](https://trello.com/c/nGH3vqgy/66-1)

**Comment by witzigs** [comment]
@guenterh 
Das sind nur Notizen, oder? Schliessen?

**Comment by guenterh** [comment]
no longer relevant
