### ISSUE TITLE
Enrichtung einer Authentfizierung für den linked / integration branch

### ISSUE THREAD

**Issue by guenterh** [swissbib/linked.integration.projekt#2]
- damit man die neuen Funktionalitäten möglichst bald im Gesamtkontext anschauen kann
- sollte shibboleth sein (was ist auf dem playground installiert bzw. funktionsfähig)
- Anpassen des deploy-scripts
- möglichst noch warten bis VF 4 produktionsfertig verteilt ist

**Comment by guenterh** [comment]
Nachdem wir die Integration in allen drei views integriert haben

devlinked.swissbib.ch
devbabe.swissbib.ch (Basel/Bern)
jusdev.swissbib.ch (juristischer content)

macht es http://jusdev.swissbib.ch/Record mehr Sinn, 

- [ ] den shibboleth Authentifizierungsmechanismus über test.swissbib.ch zu testen

- [ ] die alephgestützte Anmeldung übet devbabe.swissbib.ch anzusehen

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2](https://trello.com/c/bIBXlcpy/67-2)

**Comment by witzigs** [comment]
@guenterh 
Kann man das schliessen?

**Comment by guenterh** [comment]
nicht mehr relevant
