### ISSUE TITLE
deprecated Meldungen im deploy Prozess

### ISSUE THREAD

**Issue by guenterh** [swissbib/linked.integration.projekt#3]
npm install wirft deprecated Meldungen - wie gehen wir damit um?

Sollten wir die Konfiguration aktualisieren?

swissbib@ub-sbhp01:/usr/local/vufind/testlinked$ npm install > npm.install.log
npm WARN deprecated @types/axios@0.14.0: This is a stub types definition for axios (https://github.com/mzabriskie/axios). axios provides its own type definitions, so you don't need @types/axios installed!
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine ts-loader@3.5.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine tslint@5.9.1: wanted: {"node":">=4.8.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine webpack@3.11.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine enhanced-resolve@3.4.1: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine loader-runner@2.3.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN vufind@4.1.0 No license field.

npm run build wirft im Moment keine Meldungen

**Comment by ema-om** [comment]
Hallo zusammen,

npm run build sollte keine solchen Meldungen erzeugen, da es keine zusätzlichen Packages installiert. Diese Warnungen tauchen eigentlich nur bei der Installation von Packages mit npm install auf.

Zu den Warnungen
Ich habe gesehen, dass die package-lock.json gar nicht im Repository enthalten ist. Grundsätzlich ist es so wie bei PHP Composer, dass wo man die composer.lock immer committed, damit alle Nutzer und auch CI-Systeme alle die gleichen Paket-Versionen verwenden. Zu diesem Zweck ist es ratsam auch die package-lock.json für NPM ins Repository mit aufzunehmen.

Die Warnungen können und werden damit natürlich weder verschwinden noch in der Zukunft weniger werden. Vor allem wenn die package-lock.json im Repository landet. Damit wird alles an die Versionen in der Lock-Datei gebunden und wenn es zu den Packages Updates gibt, sobald man npm install aufruft, können diese Meldungen auftauchen.

Die Antwort wie man damit also am besten umgeht ist recht generisch: It depends! :D
Vermutlich wird es sinnvoll sein auf einem Branch einfach Tests durchzuführen, ob npm update Probleme verursacht. Entweder danach oder durch Einzelprüfung müsste man dann entscheiden, ob und wie man aktualisiert. Die Updates bekommen dann alle Nutzer und CI-Systeme postwendend mit dem nächsten Commit der package-lock.json.


Hoffe das ist hilfreich :)
Eddi

**Comment by outermedia-cbo** [comment]
Die meisten Warnungen sind durch die alte grunt Version verursacht. Wenn es keine Einwände gibt, aktualisiere ich diese.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [3](https://trello.com/c/psj4hmGs/68-3)

**Comment by witzigs** [comment]
@guenterh 
Kann das geschlossen werden?

**Comment by guenterh** [comment]
aktuell nicht mehr relevant
deploy-Prozess später nochmals anschauen, evtl upate der utilities
