### ISSUE TITLE
Vorbereiten der Integration - an was muss man denken

### ISSUE THREAD

**Issue by guenterh** [swissbib/linked.integration.projekt#4]
* wo gibt es überall Anpassungen an der Konfiguration? Darauf achten, dass diese beim Merging des abgeschlossenen Projekts übertragen werden. Beispiel auf dass ich lokal gestossen bin, als ich versuchte integration/linked in der BB view zu integrieren:
https://github.com/swissbib/vufind/blob/integration/linked/local/linked/develop/config/vufind/searches.ini#L4
Aktuell habe ich im temporär angelegten lokalen Konfigurationsverzeichnis (linked/bb/) die Einträge verdoppelt - wie man es genau macht (link auf den parent) mit Matthias absprechen

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [4](https://trello.com/c/dDF7Q9YP/69-4)

**Comment by witzigs** [comment]
@guenterh 
Das ist vollständig erledigt, oder? Kannst du schliessen?

**Comment by guenterh** [comment]
nicht mehr relevant
