### ISSUE TITLE
Konfiguration der Elasticsearch Connection

### ISSUE THREAD

**Issue by guenterh** [swissbib/linked.integration.projekt#5]
aus der Sicht jusdev.swissbib.ch haben wir im Moment keinen Zugriff auf den ES Server

Beispiel: http://jusdev.swissbib.ch/Record/504749935

@outermedia-cbo / @ema-om 
1) Wo genau wird die Konfiguration gesetzt
config_base.ini oder elasticsearch_adapter.yaml (lokalen Konfigurationspath) oder sonstwo?

2) Was müsste man machen, die Fehlermeldungen aus Ajax-Requests zu loggen oder im development-mode anzuzeigen?

**Comment by guenterh** [comment]
Mir kommt gerade in den Sinn:
der Zugriff auf ES sollte funktionieren, da die Icons I  ja im Zusammenspiel mit Ealsticsearch gesetzt werden. Das Problem bleibt dann noch: Wie bekommen wir aussagekräftigere Fehlermeldungen beim Ajaxrequest

**Comment by witzigs** [comment]
@guenterh  @ema-om @outermedia-cbo 
Das Problem auf jusdev war fehlenden config-Teilen geschuldet. Behoben mit: https://github.com/swissbib/vufind/commit/e169a9644cec50261932299e64ca4fb00437612a

**Comment by ema-om** [comment]
@Günter: Dann hat sich mein Issue den ich gerade erstellt hab ja zum Teil oder gänzlich erledigt

Von meinem iPhone gesendet

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [5](https://trello.com/c/dKKc20LS/70-5)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [5](https://trello.com/c/dKKc20LS/70-5)
