### ISSUE TITLE
whoops bei "Alle anzeigen" jusdev

### ISSUE THREAD

**Issue by guenterh** [swissbib/linked.integration.projekt#6]
@outermedia-cbo @ema-om @witzigs 
http://jusdev.swissbib.ch/Search/Results?lookfor=Verordnung+u%CC%88ber+die+Zusta%CC%88ndigkeit%2C+das+anwendbare+Recht%2C+die+Anerkennung+und+Vollstreckung+von+Entscheidungen+und+die+Zusammenarbeit+in+Unterhaltssachen&type=DEFAULT

Falls noch nicht bekannt

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [6](https://trello.com/c/8NKhsUpA/71-6)
