### ISSUE TITLE
Fehler bei alle anzeigen

### ISSUE THREAD

**Issue by guenterh** [swissbib/linked.integration.projekt#7]
Hallo @ema-om @outermedia-cbo @witzigs 

was mir gerade aufgefallen ist:

Jeweils der Aufruf mit a) gibt einen Fehler:

1) http://devlinked.swissbib.ch/Page/Detail/Subject/4020588-5
1a) http://devlinked.swissbib.ch/Search/Results?lookfor=Gesellschaft&type=DEFAULT

2) http://devlinked.swissbib.ch/Page/Detail/Subject/4015640-0
2a) http://devlinked.swissbib.ch/Search/Results?lookfor=Etymologie&type=DEFAULT

Könnt Ihr mal schauen? - Danke!

Stand von devlinked:  https://github.com/swissbib/vufind/pull/594

**Comment by outermedia-cbo** [comment]
Der type muss "Subject" lauten.

**Comment by ema-om** [comment]
Hab ich im swissbib/vufind auf dem integration/linked branch behoben und kommt mit dem nächsten PR rein

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [7](https://trello.com/c/ZTaYg8Wa/72-7)
